### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jxamen** [drnxloc/AutoLDPlayer#4]
Unable to install package 'Emgu.runtime.windows.msvc.rt.arm64 19.35.32217.1'. You are trying to install this package in a project targeting '.NETFramework,Version=v4.8', but this package does not contain any assembly references or content files compatible with that framework. Contact the package author for details.

**Comment by Dawn-dw** [comment]
Hey, hello! I just solved the problem. It was actually caused by the NuGet package management format. When I changed "Packages.config" to "PackageReference," it started working.
![image](https://github.com/drnxloc/AutoLDPlayer/assets/45678780/76a2f27b-62a0-44d5-8e9e-3872b820b7ed)

**Comment by drnxloc** [comment]
For the new Emgu Nuget package you do need to use PackageReference instead of the traditional package.config.

- Uninstall all NuGet Packages [This removes the package.config file]
- Go to Tools --> Options --> NuGet Package Manager --> General
- Change the default package management format to "PackageReference"
- Check "allow format selection on first package install"
- Click OK
- Install Emgu.CV, Emgu.CV.Bitmap, Emgu.CV.UI and Emgu.CV.runtime.windows
- These Emgu packages should now appear under your references and you should not see a package.config file.
